spring:
  application:
    name: property-bulls-data-sync

  datasource:
    username: postgres1
    password: 9IAzDlUXlP5YbNcMvPai
    url: jdbc:postgresql://postgres1.czyakgke0hox.ap-south-1.rds.amazonaws.com:5432/propertybulls
  jpa:
    hibernate:
      ddl-auto: update


realtyna:
  auth_url: https://realtyfeed-sso.auth.us-east-1.amazoncognito.com/oauth2/token
  base_url: https://api.realtyfeed.com/reso/odata
  client_id: 1t0utmqe41ksnvstdqbq6ucvkl
  grant_type: client_credentials
  client_secret: 144d23brl9a5srbfqjrgb3niuhu8l0k10qbdahmf9ltotp1p2h20
  api_key: 7OQ1wWSLot6izTWlpPVTe6PHtAzkwJrC1IMfzjPK
